### ISSUE TITLE
Feature: 发起连接后不等待 heartbeat

### ISSUE THREAD

**Issue by A-n-k-a** [nonebot/adapter-onebot#100]
mirai端使用`https://github.com/cnlimiter/onebot-mirai`插件，nonebot中使用onebot11适配器连接，发现mirai端有日志显示连接成功，但nonebot无日志输出，也无法收发消息，通过查阅代码发现onebot11适配器建立连接时会等待收到heartbeat才会创建bot对象。
尝试删除`nonebot/adapters/onebot/v11/adapter.py`中的部分代码（如下图所示）
<img width="650" alt="image" src="https://github.com/nonebot/adapter-onebot/assets/47747022/516ae74a-d375-42e7-82ea-a3afb0920aa3">
之后可以连接并收到消息且可触发插件事件，但插件尝试发送消息会报错
```
03-08 21:29:46 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bilicover, lineno=8) running complete
03-08 21:29:46 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bilicover, lineno=8) failed.
Traceback (most recent call last):
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\httpx\_transports\default.py", line 67, in map_httpcore_exceptions
    yield
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\httpx\_transports\default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 167, in handle_async_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 173, in _call_api
    response = await self.driver.request(request)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\drivers\httpx.py", line 55, in request
    response = await client.request(
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\httpx\_client.py", line 1559, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\httpx\_client.py", line 1646, in send
    response = await self._send_handling_auth(
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\httpx\_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\httpx\_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\httpx\_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\httpx\_transports\default.py", line 370, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\httpx\_transports\default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 185, in run
    uvicorn.run(
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot_plugin_bilicover\__init__.py", line 28, in bilibili_cover
    await matcher.finish("请输入BV号或AV号或视频地址")
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 574, in finish
    await cls.send(message, **kwargs)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 558, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 229, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 181, in send
    return await bot.send_msg(**params)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "D:\Portable-Program-Files\nonebot\onebot-mirai\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 187, in _call_api
    raise NetworkError("HTTP request failed") from e
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='HTTP request failed')
03-08 21:29:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bilicover, lineno=8)
03-08 21:29:46 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bilicover, lineno=8) running complete
```
因此请求添加“发起连接后是否等待heartbeat“的开关以适配onebot-mirai

**Comment by yanyongyu** [comment]
正向ws如果不发送heartbeat无法知道你的qq号是多少，所以没法连接

**Comment by A-n-k-a** [comment]
请问能否在env中主动设置正向ws的QQ号呢

**Comment by yanyongyu** [comment]
你可以使用反向ws，正向目前不能设置，因为可能会出现错误情况
