### ISSUE TITLE
onebot在指定端口上设置websocket失败

### ISSUE THREAD

**Issue by RushCN** [nonebot/adapter-onebot#110]
更换过onebot端口，仍然无法使用
env配置文件：

> HOST="127.0.0.1"
DRIVER=~fastapi+~httpx+~websockets
PORT=8080
LOG_LEVEL=DEBUG
COMMAND_START=["/"]
SUPERUSERS=["2143815408"]
ONEBOT_V12_WS_URLS=["ws://127.0.0.1:6545"]
ONEBOT_V11_WS_URLS=["ws://127.0.0.1:5456"]
ONEBOT_ACCESS_TOKEN= int = 114514
QWEATHER_APIKEY = 70a7c2dce5ae40fc8d90e379eb0b6f8d
QWEATHER_APITYPE = 0
QWEATHER_HOURLYTYPE = 2

运行日志：
> root@hcss-ecs-c534:/usr/games/GCTbot# nb run
使用 Python: /usr/games/GCTbot/.venv/bin/python
07-28 15:44:16 [SUCCESS] nonebot | NoneBot is initializing...
07-28 15:44:16 [INFO] nonebot | Current Env: prod
07-28 15:44:16 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi+~httpx+~websockets', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'2143815408'}, 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'onebot_v12_ws_urls': ['ws://127.0.0.1:6545'], 'onebot_v11_ws_urls': ['ws://127.0.0.1:5456'], 'onebot_access_token': 'int = 114514', 'qweather_apikey': '70a7c2dce5ae40fc8d90e379eb0b6f8d', 'qweather_apitype': 0, 'qweather_hourlytype': 2}
07-28 15:44:17 [DEBUG] nonebot | Succeeded to load adapter "OneBot V12"
07-28 15:44:17 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
07-28 15:44:17 [DEBUG] nonebot | Succeeded to load adapter "QQ"
07-28 15:44:17 [SUCCESS] nonebot | Succeeded to load plugin "single_session" from "nonebot.plugins.single_session"
07-28 15:44:17 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
07-28 15:44:17 [DEBUG] nonebot | Adapter "OneBot V12" already exists
07-28 15:44:17 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_guild_patch"
07-28 15:44:17 [DEBUG] nonebot | Minecraft | Model for key "/message" <class 'nonebot.adapters.minecraft.event.base.BaseChatEvent'> is overridden by <class 'nonebot.adapters.minecraft.event.base.BaseDeathEvent'>
07-28 15:44:17 [DEBUG] nonebot | Minecraft | Model for key "/notice" <class 'nonebot.adapters.minecraft.event.base.BaseJoinEvent'> is overridden by <class 'nonebot.adapters.minecraft.event.base.BaseQuitEvent'>
07-28 15:44:17 [DEBUG] nonebot | Minecraft | Model for key "/message/ServerMessageEvent" <class 'nonebot.adapters.minecraft.event.fabric.ServerMessageEvent'> is overridden by <class 'nonebot.adapters.minecraft.event.fabric.ServerMessageEvent'>
07-28 15:44:17 [DEBUG] nonebot | Minecraft | Model for key "/message" <class 'nonebot.adapters.minecraft.event.base.BaseDeathEvent'> is overridden by <class 'nonebot.adapters.minecraft.event.base.MessageEvent'>
07-28 15:44:17 [DEBUG] nonebot | Minecraft | Model for key "/notice" <class 'nonebot.adapters.minecraft.event.base.BaseQuitEvent'> is overridden by <class 'nonebot.adapters.minecraft.event.base.NoticeEvent'>
07-28 15:44:17 [DEBUG] nonebot | Minecraft | Model for key "/message/PlayerDeathEvent" <class 'nonebot.adapters.minecraft.event.forge.PlayerDeathEvent'> is overridden by <class 'nonebot.adapters.minecraft.event.spigot.PlayerDeathEvent'>
07-28 15:44:17 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mcqq"
07-28 15:44:17 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
07-28 15:44:17 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
07-28 15:44:17 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
07-28 15:44:17 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mcsm"
07-28 15:44:17 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_heweather"
07-28 15:44:17 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_status"
07-28 15:44:17 [SUCCESS] nonebot | Running NoneBot...
07-28 15:44:17 [DEBUG] nonebot | Loaded adapters: OneBot V12, OneBot V11, QQ
07-28 15:44:17 [INFO] uvicorn | Started server process [66385]
07-28 15:44:17 [INFO] uvicorn | Waiting for application startup.
07-28 15:44:18 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
07-28 15:44:18 [INFO] nonebot_plugin_htmlrender | Browser Started.
07-28 15:44:18 [DEBUG] nonebot | QQ | QQ run in sandbox mode: False
07-28 15:44:18 [DEBUG] nonebot | QQ | QQ api base url: https://api.sgroup.qq.com/
07-28 15:44:18 [INFO] uvicorn | Application startup complete.
07-28 15:44:18 [ERROR] nonebot | OneBot V12 | Error while setup websocket to ws://127.0.0.1:6545/. Trying to reconnect...
Traceback (most recent call last):
  File "/usr/games/GCTbot/bot.py", line 31, in <module>
    nonebot.run()
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v12/adapter.py", line 444, in _forward_ws
    async with self.websocket(req) as ws:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/adapter.py", line 99, in websocket
    async with self.driver.websocket(setup) as ws:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/nonebot/drivers/websockets.py", line 77, in websocket
    async with connection as ws:
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "uvloop/loop.pyx", line 2039, in create_connection
    raise exceptions[0]
  File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
    await waiter
ConnectionRefusedError: [Errno 111] Connection refused
07-28 15:44:18 [ERROR] nonebot | OneBot V11 | Error while setup websocket to ws://127.0.0.1:5456/. Trying to reconnect...
Traceback (most recent call last):
  File "/usr/games/GCTbot/bot.py", line 31, in <module>
    nonebot.run()
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 332, in _forward_ws
    async with self.websocket(request) as ws:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/adapter.py", line 99, in websocket
    async with self.driver.websocket(setup) as ws:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/nonebot/drivers/websockets.py", line 77, in websocket
    async with connection as ws:
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/usr/games/GCTbot/.venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "uvloop/loop.pyx", line 2039, in create_connection
    raise exceptions[0]
  File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
    await waiter
ConnectionRefusedError: [Errno 111] Connection refused
07-28 15:44:18 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
^C07-28 15:44:18 [INFO] uvicorn | Shutting down
07-28 15:44:18 [INFO] uvicorn | Waiting for application shutdown.
07-28 15:44:18 [INFO] nonebot_plugin_htmlrender | Browser Stopped.
07-28 15:44:18 [INFO] uvicorn | Application shutdown complete.
07-28 15:44:18 [INFO] uvicorn | Finished server process [66385]
root@hcss-ecs-c534:/usr/games/GCTbot#

**Comment by RushCN** [comment]
bot.py文件：

> import nonebot
from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter

from nonebot.adapters.qq import Adapter as QQAdapter

from nonebot.adapters.onebot.v11 import Adapter

from nonebot.adapters.onebot.v12 import Adapter

nonebot.init()

driver = nonebot.get_driver()
driver.register_adapter(Adapter)


nonebot.init()

driver = nonebot.get_driver()
driver.register_adapter(ONEBOT_V11Adapter)

driver.register_adapter(QQAdapter)

nonebot.load_builtin_plugins('echo', 'single_session')

driver = nonebot.get_driver()
driver.register_adapter(Adapter)

nonebot.load_from_toml("pyproject.toml")

if __name__ == "__main__":
    nonebot.run()

config.py文件：

> from nonebot.default_config import *

SUPERUSERS = {2143815408}

**Comment by yanyongyu** [comment]
你是不是用 ob12 连了 ob11 的协议端。。。首先确认你的协议端使用的协议版本，然后确认协议端监听的websocket端口，再确认协议端所在host的ip地址，然后再填写配置。
